platform_url = ''
api_key=''
client_id=0
connector_name=""
networkId=0
burpsuite_api_key=""
createAssetsIfZeroVulnFoundInFile=true
connector_url=""
schedule_enabled=true
schedule_type="DAILY"
hourOfDay=0
autoUrba=true