#platform_url = 'https://platform.risksense.com'
#api_key=''
client_id=1234
connector_name="myconnector"
networkId=1234
username="username"
password="password"
reportNamePrefix= ""
connector_url=""
schedule_enabled=true
schedule_type="DAILY"
hourOfDay=0
autoUrba=false