platform_url = 'https://platform.risksense.com'
api_key=''
#client_id=1234
connector_name="myconnectorname"
networkId=1234
username=""
password=""
maxdaystoretrieve= 30
connector_url=""
schedule_enabled=true
schedule_type=""
hourOfDay=10
autoUrba=false